FROM ubuntu:latest

RUN apt-get update
RUN apt-get install --no-install-recommends -y nodejs npm ca-certificates
RUN mkdir /app
WORKDIR /app
ONBUILD COPY package.json package-lock.json /app
ONBUILD RUN npm install
ONBUILD COPY . /app

EXPOSE 8080

CMD ["npm", "start"]
